version: '3'

services:
    front:
        image: node:11-alpine
        tty: true
        working_dir: /app
        volumes:
            - ./front:/app

    api:
        build:
            context: api
            dockerfile: Dockerfile.dev
        volumes:
            - ./api:/app
        environment:
            - APP_ENV=dev
            - APP_DEBUG=1
            - DATABASE_URL=pgsql://passnumerique:passnumerique@db/passnumerique?serverVersion=11
        depends_on:
            - db

    db:
        image: postgres:11-alpine
        environment:
            - POSTGRES_DB=passnumerique
            - POSTGRES_USER=passnumerique
            - POSTGRES_PASSWORD=passnumerique
