parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $cacheDir: '%kernel.cache_dir%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    GuzzleHttp\ClientInterface:
        class: 'GuzzleHttp\Client'
